"""Run Exporter Engine – generates structured JSON and executive Markdown reports."""
from __future__ import annotations

import json
from typing import Any

from backend.models.schemas import RunResult


class RunExporter:
    """Exports crew run telemetry and results into JSON or Markdown formats."""

    @staticmethod
    def to_json(run: RunResult, logs: list[str] | None = None) -> str:
        """Export run result, telemetry, and execution logs to formatted JSON."""
        data: dict[str, Any] = run.model_dump(mode="json")
        if logs is not None:
            data["logs"] = [line for line in logs if line != "__DONE__"]
        return json.dumps(data, indent=2, ensure_ascii=False)

    @staticmethod
    def to_markdown(run: RunResult, logs: list[str] | None = None) -> str:
        """Export run result, telemetry, and execution logs to a Google L5 Markdown report."""
        status_icon = {
            "completed": "✅ COMPLETED",
            "failed": "❌ FAILED",
            "running": "⏳ RUNNING",
            "pending": "🕐 PENDING",
        }.get(run.status.value, run.status.value.upper())

        started = (
            run.started_at.strftime("%Y-%m-%d %H:%M:%S UTC")
            if run.started_at
            else "Not started"
        )
        finished = (
            run.finished_at.strftime("%Y-%m-%d %H:%M:%S UTC")
            if run.finished_at
            else "In progress / Pending"
        )
        duration_str = (
            f"{run.telemetry.duration_seconds:.2f}s"
            if run.telemetry.duration_seconds is not None
            else "N/A"
        )

        md_parts = [
            f"# CrewAI Studio Execution Report: {run.crew_name.title()} Crew",
            "",
            f"> **Status:** {status_icon} | **Run ID:** `{run.run_id}`",
            "",
            "---",
            "",
            "## 1. Execution Overview & Metadata",
            "",
            "| Attribute | Value |",
            "|---|---|",
            f"| **Run ID** | `{run.run_id}` |",
            f"| **Crew Pipeline** | `{run.crew_name}` |",
            f"| **Status** | {status_icon} |",
            f"| **Execution Duration** | `{duration_str}` |",
            f"| **Started At** | {started} |",
            f"| **Finished At** | {finished} |",
            "",
            "---",
            "",
            "## 2. Telemetry & Performance Metrics",
            "",
            "| Metric | Recorded Value | Description |",
            "|---|---|---|",
            f"| **Duration** | `{duration_str}` | Total wall-clock time from kickoff to finish |",
            f"| **Log Lines Count** | `{run.telemetry.log_line_count}` | Total telemetry and execution log events captured |",
            f"| **Output Length** | `{run.telemetry.output_length} chars` | Length of compiled final deliverable |",
            f"| **Error Encountered** | `{'Yes' if run.telemetry.has_error else 'No'}` | Runtime failure flag |",
            "",
            "---",
            "",
            "## 3. Run Input Parameters",
            "",
        ]

        if run.inputs:
            md_parts.extend([
                "| Parameter | Input Value |",
                "|---|---|",
            ])
            for k, v in run.inputs.items():
                md_parts.append(f"| `{k}` | {v} |")
        else:
            md_parts.append("_No input parameters provided (default pipeline inputs used)._")

        md_parts.extend(["", "---", "", "## 4. Final Output & Deliverable", ""])

        if run.status.value == "completed" and run.output:
            md_parts.append(run.output.strip())
        elif run.status.value == "failed":
            md_parts.extend([
                "### ⚠️ Execution Error Details",
                "```text",
                run.error or "Unknown error occurred during crew execution.",
                "```",
            ])
        else:
            md_parts.append("_Run is currently running or pending completion._")

        md_parts.extend(["", "---", "", "## 5. Execution Log Trace", ""])

        cleaned_logs = [line for line in (logs or []) if line != "__DONE__"]
        if cleaned_logs:
            md_parts.append("```text")
            for log in cleaned_logs:
                md_parts.append(log)
            md_parts.append("```")
        else:
            md_parts.append("_No logs recorded for this run._")

        md_parts.extend([
            "",
            "---",
            "*Generated by CrewAI Studio Exporter Engine.*",
            "",
        ])

        return "\n".join(md_parts)
